import argparse
import os
import sys
import time

# Add current folder and 'classe' folder to PYTHONPATH for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "classe"))

from fonction import read_fasta_file, generer_first_structure, pandaspdb_vers_cif
from RNA_RASP_Optimizer import RNA_RASP_Optimizer
from RNA_DFIRE_Optimizer import RNA_DFIRE_Optimizer

def main():
    parser = argparse.ArgumentParser(description="CLI interface for 3D RNA structure full-atom optimization.")
    
    # Argument for sequence or fasta file
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-s", "--sequence", type=str, help="RNA sequence directly")
    group.add_argument("-f", "--fasta", type=str, help="Path to a FASTA file")
    
    # Argument for scoring function (restricted to full atoms for now)
    parser.add_argument("--score", type=str, choices=["rasp", "dfire"], 
                        default="dfire", help="Full-atom scoring function to use (default: dfire)")
    
    # Arguments for optimization
    optimization_group = parser.add_argument_group("Optimization Parameters")
    optimization_group.add_argument("--epochs", type=int, default=50, help="Number of epochs per cycle (default: 50)")
    optimization_group.add_argument("--cycles", type=int, default=20, help="Number of cycles (default: 20)")
    optimization_group.add_argument("--lr", type=float, default=0.2, help="Learning rate (default: 0.2)")
    optimization_group.add_argument("--noise-coords", type=float, default=0.5, help="Noise on coordinates (default: 0.5)")
    optimization_group.add_argument("--noise-angles", type=float, default=0.2, help="Noise on angles (default: 0.2)")
    optimization_group.add_argument("--backbone-weigsur un autreht", type=float, default=100.0, help="Weight for backbone constraints (default: 100.0)")
    optimization_group.add_argument("--clash-weight", type=float, default=50.0, help="Weight for clash constraints (default: 50.0)")
    optimization_group.add_argument("--ref-atom", type=str, default="C3'", help="Reference atom for potential evaluation (default: C3')")

    # Arguments for output and display
    output_group = parser.add_argument_group("Output Parameters")
    output_group.add_argument("-o", "--output", type=str, help="Name of the output file (default: autogenerated in 'resultat' folder)")
    output_group.add_argument("-v", "--verbose", action="store_true", help="Verbose output during optimization")
    output_group.add_argument("--export_type", type=str, default="pdb", choices = ["pdb", "cif"], help="Type of file to export (default: pdb)")
    
    args = parser.parse_args()

    # 1. Sequence retrieval
    sequence = ""
    if args.fasta:
        print(f"Reading FASTA file: {args.fasta}")
        try:
            from Bio import SeqIO
            record = next(SeqIO.parse(args.fasta, "fasta"))
            sequence = str(record.seq).upper().replace("T", "U")
        except Exception as e:
            print(f"Error reading FASTA: {e}")
            sys.exit(1)
    else:
        sequence = args.sequence.upper().replace("T", "U")

    print(f"Sequence loaded ({len(sequence)} nuc): {sequence[:50]}...")

    # 2. Initial structure generation
    os.makedirs("fichier_arn", exist_ok=True)
    os.makedirs("resultat", exist_ok=True)
    
    initial_pdb = f"fichier_arn/initial_{int(time.time())}.pdb"
    generer_first_structure(sequence, initial_pdb)
    
    print("Generating initial straight structure...")
    
    if not os.path.exists(initial_pdb):
        print("Error: Initial structure could not be generated.")
        sys.exit(1)
        


    # 3. Optimizer selection
    if args.output:
        output_path = f"resultat/{args.output}.{args.export_type}"
    else:
        output_path = f"resultat/optimized_{args.score}_{int(time.time())}.{args.export_type}"
    
    # Security check: if output_path is a directory, append a default filename
    if os.path.isdir(output_path) or output_path.endswith('/'):
        os.makedirs(output_path, exist_ok=True)
        filename = f"optimized_{args.score}_{int(time.time())}.{args.export_type}"
        output_path = os.path.join(output_path, filename)
    elif not output_path.lower().endswith(f".{args.export_type}"):
        output_path += f".{args.export_type}"

    optimizer_classes = {
        "rasp": RNA_RASP_Optimizer,
        "dfire": RNA_DFIRE_Optimizer
    }
    
    OptClass = optimizer_classes[args.score]
    
    print(f"Initializing {args.score} optimizer (full atoms)...")
    
    # Unified call for full-atom optimizers
    # Passing everything as named arguments for Clarity
    opt = OptClass(
            nbre_nt_exclu=2,
            pdb_path=initial_pdb,
            epochs_per_cycle=args.epochs,
            lr=args.lr,
            output_path=output_path,
            ref_atom=args.ref_atom,
            num_cycles=args.cycles,
            noise_coords=args.noise_coords,
            noise_angles=args.noise_angles,
            backbone_weight=args.backbone_weight,
            clash_weight=args.clash_weight,
            verbose=args.verbose
        )

    # 4. Optimization run
    print("\n--- Starting optimization ---")
    start_time = time.perf_counter()
    result, best_score = opt.run_optimization()
    end_time = time.perf_counter()
    print("--- Optimization finished ---")
    
    # Exporting according to requested format
    if args.export_type == "pdb":
        result.to_pdb(output_path)
    elif args.export_type == "cif":
        pandaspdb_vers_cif(result, output_path)
        
    print(f"Best score obtained: {best_score}")
    print(f"Result saved in: {output_path}")
    print(f"Execution time: {end_time - start_time:.2f} seconds")

if __name__ == "__main__":
    main()
