import os
import subprocess
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt 
from biopandas.pdb import PandasPdb
import nglview as nv
from Bio import SeqIO
from Bio.PDB import PDBParser, PDBIO, Atom, MMCIFIO
import sys

def view_structure(file_pdb):
    # 1. Load the generated file
    view = nv.show_file(file_pdb)
    # 2. Clear default representations
    view.clear_representations()
    # 3. Display the entire molecule in detail
    view.add_representation('licorice', selection='all', color='element')
    # 4. Special highlight for Phosphorus atoms (nodes of phosphodiester bonds)
    view.add_representation('spacefill', selection='_P', color='orange', radius=0.8)
    # 5. Add a "tube" that follows and continuously highlights the phosphodiester backbone
    view.add_representation('tube', selection='backbone', color='red', radius=0.2)
    # 6. Center the view
    view.center()
    # Display the interface
    return view

def enlever_hydrogene(file_pdb, output_file_pdb):
    ppdb_df =  PandasPdb().read_pdb(file_pdb)
    atom_df = ppdb_df.df["ATOM"]
    atom_sans_h_df = atom_df[~atom_df["atom_name"].str.startswith("H")]
    ppdb_df.df['ATOM'] = atom_sans_h_df
    ppdb_df.to_pdb(output_file_pdb)

def generer_arn_droit(sequence, fichier_sortie="arn_structure.pdb"):
    """
    Generates a PDB file of a straight (canonical) single-strand RNA from 
    a nucleotide sequence.
    Requires AmberTools ('tleap' installed and in PATH).
    """
    # 1. Format the sequence for tleap
    # To avoid syntax errors with very long sequences,
    # we split the sequence into chunks of 50 nucleotides.
    taille_chunk = 50
    chunks = [sequence[i:i + taille_chunk] for i in range(0, len(sequence), taille_chunk)]
    
    script_tleap = "instructions_tleap.in"
    
    # 2. Créer le script d'instructions que l'on passera à tleap
    with open(script_tleap, "w") as f:
        # Charger le champ de force pour l'ARN (OL3 est le standard très recommandé)
        f.write("source leaprc.RNA.OL3\n")
        
        # Construire chaque morceau de la séquence
        noms_parties = []
        for i, chunk in enumerate(chunks):taille_chunk = 50
    chunks = [sequence[i:i + taille_chunk] for i in range(0, len(sequence), taille_chunk)]
    
    script_tleap = "instructions_tleap.in"
    
    # 2. Créer le script d'instructions que l'on passera à tleap
    with open(script_tleap, "w") as f:
        # Charger le champ de force pour l'ARN (OL3 est le standard très recommandé)
        f.write("source leaprc.RNA.OL3\n")
        
        # Construire chaque morceau de la séquence
        noms_parties = []
        for i, chunk in enumerate(chunks):
            chunk_formatee = " ".join([nuc.upper() for nuc in chunk])
            nom_partie = f"partie_{i}"
            f.write(f"{nom_partie} = sequence {{ {chunk_formatee} }}\n")
            noms_parties.append(nom_partie)
        
        # Combine all pieces into a "mon_arn" variable
        liste_parties = " ".join(noms_parties)
        f.write(f"mon_arn = combine {{ {liste_parties} }}\n")
        
        # Export the molecule in PDB format
        f.write(f"savepdb mon_arn {fichier_sortie}\n")
        
        # Quit the program
        f.write("quit\n")
        
    print(f"Generating structure for sequence ({len(sequence)} nuc): {sequence[:50]}...")
    
    # 3. Run tleap from Python as a subprocess
    try:
        # Note: tleap must be in your PATH (usually after conda activate Stage)
        process = subprocess.run(
            ["tleap", "-f", script_tleap], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            check=True,
            text=True
        )
        print(f"Success! The file '{fichier_sortie}' has been created.")
        
    except FileNotFoundError:
        print("Error: 'tleap' not found.")
        print("Make sure you have activated your environment with conda: conda activate Stage")
    except subprocess.CalledProcessError as e:
        print("Error during tleap execution!")
        print("stdout details:", e.stdout)
        print("stderr details:", e.stderr)
        
    finally:
        # 4. Clean up temporary files generated by AmberTools
        if os.path.exists(script_tleap):
            os.remove(script_tleap)
        if os.path.exists("leap.log"):
            os.remove("leap.log")

def read_fasta_file (fasta_file):
    if not os.path.exists(fasta_file):
        raise FileNotFoundError(f"The file {fasta_file} does not exist.")
    sequences = []
    nom = []
    records = list(SeqIO.parse(fasta_file, "fasta"))
    for record in records:
        sequences.append(record.seq)
        nom.append(record.id)
    return sequences, nom

def fix_amber_pdb(input_pdb, output_pdb):
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure('rna', input_pdb)

    # Traverse the structure to find the first residue
    for model in structure:
        for chain in model:
            # Get the first residue (often ID 1)
    # On récupère le premier résidu (souvent l'id 1)
            first_residue = next(chain.get_residues())
            
            if 'P' in first_residue and 'OP3' not in first_residue:
                # Get the OP2 atom to copy its properties
                if 'OP2' in first_residue:
                    op2 = first_residue['OP2']
                    coord = op2.get_coord()
                    
                    # Create the new OP3 atom
                    # Slightly offset OP2 coordinates
                    new_coord = coord + [0.5, 0.5, 0.5]
                    
                    op3 = Atom.Atom(
                        name='OP3',
                        coord=new_coord,
                        bfactor=op2.get_bfactor(),   # Use bfactor, not B
                        occupancy=op2.get_occupancy(),
                        altloc=op2.get_altloc(),
                        fullname=' OP3',
                        serial_number=3,             # Optional
                        element='O'
                    )
                    
                    first_residue.add(op3)
                    print(f"OP3 added to residue {first_residue.get_resname()} {first_residue.id[1]}")

    # Clean file rewrite
    io = PDBIO()
    io.set_structure(structure)
    io.save(output_pdb)

def generer_first_structure(sequence, fichier_sortie="arn_structure.pdb"):
    print('Generate the first 3D structure')
    generer_arn_droit(sequence, fichier_sortie)
    enlever_hydrogene(fichier_sortie, fichier_sortie)
    fix_amber_pdb(fichier_sortie, fichier_sortie)
    print("The structure was been generated")

def pandaspdb_vers_cif(ppdb_obj, nom_sortie):
    # 1. Fill missing or problematic columns for CIF format
    # CIF format often requires explicit values for asym_id and entity_id
    if 'chain_id' in ppdb_obj.df['ATOM'].columns:
        # Biopython uses 'label_asym_id' and 'label_entity_id' in CIF
        # Ensure chain_id is not empty
        ppdb_obj.df['ATOM']['chain_id'] = ppdb_obj.df['ATOM']['chain_id'].replace('', 'A').fillna('A')
    
    # 2. Save PandasPdb object to template file
    # 2. Sauvegarder l'objet PandasPdb en fichier temporaire
    temp_pdb = "temp_transformation.pdb"
    ppdb_obj.to_pdb(temp_pdb)
    
    # 3. Use Biopython to read this file
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("RNA", temp_pdb)
    
    # 4. Traverse the structure to ensure fields are filled
    for model in structure:
        for chain in model:
            # Force chain ID if empty or default
            if not chain.id or chain.id == ' ':
                chain.id = 'A'
    
    # 5. Save as mmCIF
    io = MMCIFIO()
    io.set_structure(structure)
    io.save(nom_sortie)
    
    # 6. Clean up temporary file
    if os.path.exists(temp_pdb):
        os.remove(temp_pdb)

def plot_interpolation_dist(score_type, res1, atom1, res2, atom2, seq_sep=1, num_beads=50, save_path=None):
    """
    Trace l'interpolation de l'énergie (DFIRE, RASP, ou rsRNASP) EXACTEMENT telle qu'elle est 
    implémentée dans les classes BeadSpring respectives (Catmull-Rom, clamping, cutoff, poids).
    """
    import os
    import torch
    import numpy as np
    import matplotlib.pyplot as plt

    # Importation locale des parseurs
    from parse_dfire_potentials import load_dfire_potentials, get_dfire_type
    from parse_rasp_potentials import load_rasp_potentials, get_rasp_type
    from parse_rsrnasp_potentials import load_rsrnasp_potentials, get_rsrnasp_type

    device = torch.device("cpu")
    
    # Génération d'un vecteur de distances
    dists_np = np.linspace(0.1, 30.0, 800)
    dists = torch.tensor(dists_np, dtype=torch.float32, device=device)
    
    score_type = score_type.lower()
    
    if score_type == "dfire":
        path = "potentials/matrice_dfire.dat"
        if not os.path.exists(path):
            print(f"Fichier introuvable: {path}")
            return
            
        dict_pots = load_dfire_potentials(path)
        
        all_types = set()
        for t1, t2 in dict_pots.keys():
            all_types.add(t1)
            all_types.add(t2)
        sorted_types = sorted(list(all_types))
        type_to_idx = {t: i for i, t in enumerate(sorted_types)}
        num_types = len(sorted_types)
        num_bins = len(next(iter(dict_pots.values())))
        
        potential_tensor = torch.zeros((num_types, num_types, num_bins), dtype=torch.float32, device=device)
        for (t1, t2), values in dict_pots.items():
            if t1 in type_to_idx and t2 in type_to_idx:
                idx1 = type_to_idx[t1]
                idx2 = type_to_idx[t2]
                potential_tensor[idx1, idx2, :] = torch.tensor(values, dtype=torch.float32)
                potential_tensor[idx2, idx1, :] = torch.tensor(values, dtype=torch.float32)
                
        type1 = type_to_idx.get(get_dfire_type(atom1, res1), 0)
        type2 = type_to_idx.get(get_dfire_type(atom2, res2), 0)
        
        # Logique exacte de BeadSpringDFIREOptimizer
        step = 0.7
        max_dist = 19.6
        
        d_scaled = dists / step
        d_clamp = torch.clamp(d_scaled, 0.0, float(num_bins - 1.0001))
        
        i = torch.floor(d_clamp).long()
        t = d_clamp - i.float()
        
        idx0 = torch.clamp(i - 1, min=0)
        idx1 = i
        idx2 = torch.clamp(i + 1, max=num_bins - 1)
        idx3 = torch.clamp(i + 2, max=num_bins - 1)
        
        p0 = potential_tensor[type1, type2, idx0]
        p1 = potential_tensor[type1, type2, idx1]
        p2 = potential_tensor[type1, type2, idx2]
        p3 = potential_tensor[type1, type2, idx3]
        
        t2 = t * t
        t3 = t2 * t
        
        f0 = -0.5 * t3 + t2 - 0.5 * t
        f1 = 1.5 * t3 - 2.5 * t2 + 1.0
        f2 = -1.5 * t3 + 2.0 * t2 + 0.5 * t
        f3 = 0.5 * t3 - 0.5 * t2
        
        interp_energy = f0 * p0 + f1 * p1 + f2 * p2 + f3 * p3
        cutoff = torch.sigmoid(2.0 * (max_dist - dists))
        score = interp_energy * cutoff
        
        raw_x = np.arange(num_bins) * step
        raw_y = potential_tensor[type1, type2, :].cpu().numpy()
        title = f"DFIRE Interpolation (Catmull-Rom)\n{res1}-{atom1} vs {res2}-{atom2}\nClamped at edges, Sigmoid Cutoff at {max_dist}Å"
        
    elif score_type == "rasp":
        path = "potentials/all.nrg"
        if not os.path.exists(path):
            print(f"Fichier introuvable: {path}")
            return
            
        taille_mat, dict_pots = load_rasp_potentials(path)
        
        potential_tensor = torch.zeros(taille_mat, dtype=torch.float32, device=device)
        for (k, t1, t2, dist), energy in dict_pots.items():
            if k < taille_mat[0] and t1 < taille_mat[1] and t2 < taille_mat[2] and dist < taille_mat[3]:
                potential_tensor[k, t1, t2, dist] = energy
                potential_tensor[k, t2, t1, dist] = energy
                
        type1 = get_rasp_type(res1, atom1, "all")
        type2 = get_rasp_type(res2, atom2, "all")
        if type1 == -1: type1 = 0
        if type2 == -1: type2 = 0
        
        # Logique exacte de BeadSpringRASPOptimizer
        # On bride la valeur k_val à la taille maximale de la matrice chargée (all.nrg = 5)
        k_max = potential_tensor.size(0) - 1
        k_val = min(seq_sep, k_max)
        
        max_idx = potential_tensor.size(3) - 1
        d_clamp = torch.clamp(dists, 0.5, float(max_idx - 1.5))
        d0 = torch.floor(d_clamp).long()
        d1 = d0 + 1
        alpha = d_clamp - d0.float()
        
        im1 = torch.clamp(d0 - 1, min=0)
        i2 = torch.clamp(d1 + 1, max=max_idx)
        
        p0 = potential_tensor[k_val, type1, type2, im1]
        p1 = potential_tensor[k_val, type1, type2, d0]
        p2 = potential_tensor[k_val, type1, type2, d1]
        p3 = potential_tensor[k_val, type1, type2, i2]
        
        interp_energy = 0.5 * (
            (2 * p1) + (-p0 + p2) * alpha +
            (2 * p0 - 5 * p1 + 4 * p2 - p3) * alpha**2 +
            (-p0 + 3 * p1 - 3 * p2 + p3) * alpha**3
        )
        
        cutoff = torch.sigmoid(2.0 * (19.0 - dists))
        score = interp_energy * cutoff
        
        raw_x = np.arange(max_idx + 1)
        raw_y = potential_tensor[k_val, type1, type2, :].cpu().numpy()
        title = f"RASP Interpolation (Catmull-Rom)\n{res1}-{atom1} vs {res2}-{atom2}\nseq_sep={seq_sep} => k_val={k_val}, Sigmoid Cutoff at 19.0Å"
        
    elif score_type == "rsrnasp":
        short_path = "potentials/short-ranged.potential"
        long_path = "potentials/long-ranged.potential"
        if not os.path.exists(short_path) or not os.path.exists(long_path):
            print(f"Fichiers introuvables: {short_path}, {long_path}")
            return
            
        num_types, num_bins, dict_pots = load_rsrnasp_potentials(short_path, long_path)
        
        potential_tensor = torch.zeros((2, num_types, num_types, num_bins), dtype=torch.float32, device=device)
        for (k_state, t1, t2, dist_bin), energy in dict_pots.items():
            potential_tensor[k_state, t1, t2, dist_bin] = energy
            
        type1 = get_rsrnasp_type(res1, atom1)
        type2 = get_rsrnasp_type(res2, atom2)
        if type1 == -1: type1 = 0
        if type2 == -1: type2 = 0
        
        # Logique exacte de BeadSpringRsRNASPOptimizer
        step_distance = 0.3
        cutoff_short = 13.0
        cutoff_long = 24.0
        
        f_N = (-2685.0 / ((num_beads + 16.0) ** 0.5)) + 542.0
        w_long = 16.0 / f_N if f_N != 0 else 1.0
        
        k_state = 1 if seq_sep >= 5 else 0
        
        d_scaled = dists / step_distance
        max_idx = potential_tensor.size(3) - 1
        d_clamp = torch.clamp(d_scaled, 0.5, float(max_idx - 1.5))
        d0 = torch.floor(d_clamp).long()
        d1 = d0 + 1
        alpha = d_clamp - d0.float()
        
        im1 = torch.clamp(d0 - 1, min=0)
        i2 = torch.clamp(d1 + 1, max=max_idx)
        
        p0 = potential_tensor[k_state, type1, type2, im1]
        p1 = potential_tensor[k_state, type1, type2, d0]
        p2 = potential_tensor[k_state, type1, type2, d1]
        p3 = potential_tensor[k_state, type1, type2, i2]
        
        interp_energy = 0.5 * (
            (2 * p1) + (-p0 + p2) * alpha +
            (2 * p0 - 5 * p1 + 4 * p2 - p3) * alpha**2 +
            (-p0 + 3 * p1 - 3 * p2 + p3) * alpha**3
        )
        
        cutoff_val = cutoff_long if k_state == 1 else cutoff_short
        topological_weight = w_long if k_state == 1 else 1.0
        
        cutoff_weights = torch.sigmoid(2.0 * (cutoff_val - dists))
        score = interp_energy * cutoff_weights * topological_weight
        
        raw_x = np.arange(num_bins) * step_distance
        raw_y = potential_tensor[k_state, type1, type2, :].cpu().numpy()
        title = f"rsRNASP Interpolation (Catmull-Rom)\n{res1}-{atom1} vs {res2}-{atom2}\nseq_sep={seq_sep} => k_state={k_state}, w={topological_weight:.2f}, cutoff={cutoff_val}Å"
        
    else:
        print(f"Type de score inconnu: {score_type}. Utilisez 'dfire', 'rasp' ou 'rsrnasp'.")
        return
        
    # Plot final
    plt.figure(figsize=(10, 6))
    
    # Points discrets de la matrice
    plt.plot(raw_x, raw_y, 'o', label=f"{score_type.upper()} Points Matrice", color="black", alpha=0.5, markersize=4)
        
    # Courbe continue interpolée et modifiée (cutoff + poids)
    plt.plot(dists_np, score.cpu().numpy(), '-', label=f"Interpolation + ajustements\n(telle qu'optimisée par BeadSpring)", color="red", linewidth=2)
    
    plt.title(title)
    plt.xlabel(f"Distance (Å)")
    plt.ylabel("Énergie")
    plt.legend()
    plt.grid(alpha=0.3)
    
    # Ajustement de l'axe y pour voir correctement
    y_min = max(-5, min(raw_y) * 1.5)
    y_max = min(20, max(raw_y) * 1.1)
    
    # Fallback au cas où tout est à 0 (types invalides etc.)
    if y_min == y_max == 0:
        y_min, y_max = -1, 1
        
    plt.ylim(y_min, y_max)
    plt.xlim(0, 30)
    
    if save_path:
        plt.savefig(save_path)
    plt.show()