import os
import subprocess
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt 
from biopandas.pdb import PandasPdb
import nglview as nv
from Bio import SeqIO
from Bio.PDB import PDBParser, PDBIO, Atom, MMCIFIO
import sys

def view_structure(file_pdb):
    # 1. Load the generated file
    view = nv.show_file(file_pdb)
    # 2. Clear default representations
    view.clear_representations()
    # 3. Display the entire molecule in detail
    view.add_representation('licorice', selection='all', color='element')
    # 4. Special highlight for Phosphorus atoms (nodes of phosphodiester bonds)
    view.add_representation('spacefill', selection='_P', color='orange', radius=0.8)
    # 5. Add a "tube" that follows and continuously highlights the phosphodiester backbone
    view.add_representation('tube', selection='backbone', color='red', radius=0.2)
    # 6. Center the view
    view.center()
    # Display the interface
    return view

def enlever_hydrogene(file_pdb, output_file_pdb):
    ppdb_df =  PandasPdb().read_pdb(file_pdb)
    atom_df = ppdb_df.df["ATOM"]
    atom_sans_h_df = atom_df[~atom_df["atom_name"].str.startswith("H")]
    ppdb_df.df['ATOM'] = atom_sans_h_df
    ppdb_df.to_pdb(output_file_pdb)

def generer_arn_droit(sequence, fichier_sortie="arn_structure.pdb"):
    """
    Generates a PDB file of a straight (canonical) single-strand RNA from 
    a nucleotide sequence.
    Requires AmberTools ('tleap' installed and in PATH).
    """
    # 1. Format the sequence for tleap
    # To avoid syntax errors with very long sequences,
    # we split the sequence into chunks of 50 nucleotides.
    taille_chunk = 50
    chunks = [sequence[i:i + taille_chunk] for i in range(0, len(sequence), taille_chunk)]
    
    script_tleap = "instructions_tleap.in"
    
    # 2. Créer le script d'instructions que l'on passera à tleap
    with open(script_tleap, "w") as f:
        # Charger le champ de force pour l'ARN (OL3 est le standard très recommandé)
        f.write("source leaprc.RNA.OL3\n")
        
        # Construire chaque morceau de la séquence
        noms_parties = []
        for i, chunk in enumerate(chunks):taille_chunk = 50
    chunks = [sequence[i:i + taille_chunk] for i in range(0, len(sequence), taille_chunk)]
    
    script_tleap = "instructions_tleap.in"
    
    # 2. Créer le script d'instructions que l'on passera à tleap
    with open(script_tleap, "w") as f:
        # Charger le champ de force pour l'ARN (OL3 est le standard très recommandé)
        f.write("source leaprc.RNA.OL3\n")
        
        # Construire chaque morceau de la séquence
        noms_parties = []
        for i, chunk in enumerate(chunks):
            chunk_formatee = " ".join([nuc.upper() for nuc in chunk])
            nom_partie = f"partie_{i}"
            f.write(f"{nom_partie} = sequence {{ {chunk_formatee} }}\n")
            noms_parties.append(nom_partie)
        
        # Combine all pieces into a "mon_arn" variable
        liste_parties = " ".join(noms_parties)
        f.write(f"mon_arn = combine {{ {liste_parties} }}\n")
        
        # Export the molecule in PDB format
        f.write(f"savepdb mon_arn {fichier_sortie}\n")
        
        # Quit the program
        f.write("quit\n")
        
    print(f"Generating structure for sequence ({len(sequence)} nuc): {sequence[:50]}...")
    
    # 3. Run tleap from Python as a subprocess
    try:
        # Note: tleap must be in your PATH (usually after conda activate Stage)
        process = subprocess.run(
            ["tleap", "-f", script_tleap], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            check=True,
            text=True
        )
        print(f"Success! The file '{fichier_sortie}' has been created.")
        
    except FileNotFoundError:
        print("Error: 'tleap' not found.")
        print("Make sure you have activated your environment with conda: conda activate Stage")
    except subprocess.CalledProcessError as e:
        print("Error during tleap execution!")
        print("stdout details:", e.stdout)
        print("stderr details:", e.stderr)
        
    finally:
        # 4. Clean up temporary files generated by AmberTools
        if os.path.exists(script_tleap):
            os.remove(script_tleap)
        if os.path.exists("leap.log"):
            os.remove("leap.log")

def read_fasta_file (fasta_file):
    if not os.path.exists(fasta_file):
        raise FileNotFoundError(f"The file {fasta_file} does not exist.")
    sequences = []
    nom = []
    records = list(SeqIO.parse(fasta_file, "fasta"))
    for record in records:
        sequences.append(record.seq)
        nom.append(record.id)
    return sequences, nom

def fix_amber_pdb(input_pdb, output_pdb):
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure('rna', input_pdb)

    # Traverse the structure to find the first residue
    for model in structure:
        for chain in model:
            # Get the first residue (often ID 1)
    # On récupère le premier résidu (souvent l'id 1)
            first_residue = next(chain.get_residues())
            
            if 'P' in first_residue and 'OP3' not in first_residue:
                # Get the OP2 atom to copy its properties
                if 'OP2' in first_residue:
                    op2 = first_residue['OP2']
                    coord = op2.get_coord()
                    
                    # Create the new OP3 atom
                    # Slightly offset OP2 coordinates
                    new_coord = coord + [0.5, 0.5, 0.5]
                    
                    op3 = Atom.Atom(
                        name='OP3',
                        coord=new_coord,
                        bfactor=op2.get_bfactor(),   # Use bfactor, not B
                        occupancy=op2.get_occupancy(),
                        altloc=op2.get_altloc(),
                        fullname=' OP3',
                        serial_number=3,             # Optional
                        element='O'
                    )
                    
                    first_residue.add(op3)
                    print(f"OP3 added to residue {first_residue.get_resname()} {first_residue.id[1]}")

    # Clean file rewrite
    io = PDBIO()
    io.set_structure(structure)
    io.save(output_pdb)

def generer_first_structure(sequence, fichier_sortie="arn_structure.pdb"):
    print('Generate the first 3D structure')
    generer_arn_droit(sequence, fichier_sortie)
    enlever_hydrogene(fichier_sortie, fichier_sortie)
    fix_amber_pdb(fichier_sortie, fichier_sortie)
    print("The structure was been generated")

def pandaspdb_vers_cif(ppdb_obj, nom_sortie):
    # 1. Fill missing or problematic columns for CIF format
    # CIF format often requires explicit values for asym_id and entity_id
    if 'chain_id' in ppdb_obj.df['ATOM'].columns:
        # Biopython uses 'label_asym_id' and 'label_entity_id' in CIF
        # Ensure chain_id is not empty
        ppdb_obj.df['ATOM']['chain_id'] = ppdb_obj.df['ATOM']['chain_id'].replace('', 'A').fillna('A')
    
    # 2. Save PandasPdb object to template file
    # 2. Sauvegarder l'objet PandasPdb en fichier temporaire
    temp_pdb = "temp_transformation.pdb"
    ppdb_obj.to_pdb(temp_pdb)
    
    # 3. Use Biopython to read this file
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("RNA", temp_pdb)
    
    # 4. Traverse the structure to ensure fields are filled
    for model in structure:
        for chain in model:
            # Force chain ID if empty or default
            if not chain.id or chain.id == ' ':
                chain.id = 'A'
    
    # 5. Save as mmCIF
    io = MMCIFIO()
    io.set_structure(structure)
    io.save(nom_sortie)
    
    # 6. Clean up temporary file
    if os.path.exists(temp_pdb):
        os.remove(temp_pdb)